feat: ability to set JWT claim used for EntityID
statnett/vault-plugin-auth-jwt-auto-roles pull request #60
Opened 2024-03-18 13:13 UTC by tenstad

2024-03-18 15:15 UTC, erikgb requested changes

2024-03-18 15:15 UTC, erikgb commented on internal/jwtauth/path_config.go
> +					Name: "Key in JWT claims to use for auth alias id",
```suggestion
					Name: "Claim in JWT claims to use for user/username",
```

2024-03-18 15:25 UTC, tenstad commented on internal/jwtauth/path_config.go
> +					Name: "Claim in JWT claims to use for user/username",
```suggestion
					Name: "Claim in JWT claims to use for auth alias name",
```

2024-03-19 07:27 UTC, erikgb submitted a review, later dismissed

2024-03-19 07:34 UTC, tenstad commented on internal/jwtauth/path_config.go
> +					Name: "Claim in JWT claims to use for auth alias name",
What are you thinking? I'm up for _entity alias name_ instead, using the GUI term instead of the current code/sdk term.

2024-03-19 08:20 UTC, tenstad commented on internal/jwtauth/path_config.go
> +					Name: "Claim in JWT claims to use for auth alias name",
```suggestion
					Name: "Claim in JWT claims to use for entity alias name",
```

2024-03-19 09:51 UTC, erikgb approved these changes

2024-03-19 10:25 UTC, merged